In [1]:
import pandas as pd
import re
from driver import clean_text

corpus = pd.read_excel("Data/corpus.xlsx")
corpus["text_content"] = corpus["text_content"].apply(lambda x: clean_text(x))
corpus.head()

,doc_id,url,html_content,text_content,scraping_source
0,d0,https://wwftravel.it/blog/viaggi/india-natura-...,"<body><p>""\n</p>\n<a class=""skip-link screen-r...",Vai al contenuto Home Blog Viaggi India natura...,manual-scraped
1,d1,https://www.terreincognitemagazine.it/natura-s...,"<body class=""single single-post postid-2526 si...",Homepage > CULTURA > MOSTRE > Natura selvaggia...,auto-scraped
2,d2,https://www.storicang.it/a/civilta-dellindo-i-...,"<body><p>""\n</p><div aria-hidden=""true"" class=...",La prospera civiltà della valle dell'Indo creb...,manual-scraped
3,d3,https://www.focusjunior.it/scuola/storia/chi-s...,"<body><div id=""fb-root""></div>\n<noscript></no...",FocusJunior.it Scuola Storia Chi sono gli Indi...,auto-scraped
4,d4,https://www.focusjunior.it/comportamento/feste...,"<body><div id=""fb-root""></div>\n<noscript></no...",FocusJunior.it Comportamento Feste Festa della...,auto-scraped

In [2]:
from driver import get_text_stats

text_stat_results = get_text_stats(corpus, "text_content")

corpus["content_len"] = text_stat_results["content_len"]
corpus["mean_aoa"] = text_stat_results["mean_aoa"]
corpus["mean_conc"] = text_stat_results["mean_conc"]
corpus["gulpease_index"] = text_stat_results["gulpease_index"]
corpus["fres"] = text_stat_results["fres"]

  0%|          | 0/221 [00:00<?, ?it/s]

c:\Users\hrishitachakra\AppData\Local\anaconda3\envs\pt_env\lib\site-packages\numpy\_core\fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
c:\Users\hrishitachakra\AppData\Local\anaconda3\envs\pt_env\lib\site-packages\numpy\_core\_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

In [3]:
corpus.to_excel("Data/analysed_corpus.xlsx", index=False)

In [4]:
corpus.head()

,doc_id,url,html_content,text_content,scraping_source,content_len,mean_aoa,mean_conc,gulpease_index,fres
0,d0,https://wwftravel.it/blog/viaggi/india-natura-...,"<body><p>""\n</p>\n<a class=""skip-link screen-r...",Vai al contenuto Home Blog Viaggi India natura...,manual-scraped,1389,5.107979,6.499554,51.666813,66.401379
1,d1,https://www.terreincognitemagazine.it/natura-s...,"<body class=""single single-post postid-2526 si...",Homepage > CULTURA > MOSTRE > Natura selvaggia...,auto-scraped,1644,5.299357,6.255435,44.195174,45.238045
2,d2,https://www.storicang.it/a/civilta-dellindo-i-...,"<body><p>""\n</p><div aria-hidden=""true"" class=...",La prospera civiltà della valle dell'Indo creb...,manual-scraped,1635,5.391870,6.594318,43.365193,39.961271
3,d3,https://www.focusjunior.it/scuola/storia/chi-s...,"<body><div id=""fb-root""></div>\n<noscript></no...",FocusJunior.it Scuola Storia Chi sono gli Indi...,auto-scraped,1724,5.276939,6.335433,47.746429,52.850800
4,d4,https://www.focusjunior.it/comportamento/feste...,"<body><div id=""fb-root""></div>\n<noscript></no...",FocusJunior.it Comportamento Feste Festa della...,auto-scraped,1140,4.129123,6.899603,52.684927,66.465536