In [7]:
import json
import pandas as pd
import glob
import numpy as np
import driver
import spacy
nlp = spacy.load("it_core_news_sm")

In [8]:
final_answer_df = pd.DataFrame()

for file_name in glob.glob("Data/3rd/*_FULL.log"):
    # print(file_name)
    with open(file_name, 'r') as f:
        result = [json.loads(x) for x in f.readlines()]

    ## final answers
    final_answer_temp_df = driver.get_final_answers(result)
    final_answer_df = pd.concat([final_answer_df, final_answer_temp_df], ignore_index=True)

for file_name in glob.glob("Data/4th/*_FULL.log"):
    ## final answers
    # print(file_name)
    with open(file_name, 'r') as f:
        result = [json.loads(x) for x in f.readlines()]

    final_answer_temp_df = driver.get_final_answers(result)
    final_answer_df = pd.concat([final_answer_df, final_answer_temp_df], ignore_index=True)

final_answer_df = final_answer_df.drop_duplicates(ignore_index=True)
final_answer_df.head()

,uid,topic_number,prompt,answer,timestamp
0,17,g3t3,Quali sono 5 animali tipici dell'India?,Pavone tigre 🐅 scimmia 🐵 leone cobra,2026-05-19 14:55:32.736
1,17,g3t2,Qual è il nome del simbolo al centro della ban...,"Rapreseta la ruota dellavitabhuddista, si chia...",2026-05-19 15:22:09.501
2,17,g3t1,Come si chiama il fiume sacro agli indiani?,Il fiume si chiama gange,2026-05-19 15:27:44.380
3,18,g3t3,Quali sono 5 animali tipici dell'India?,"Tigre del bengala ,Leone asiatico ,rinoceronte...",2026-05-19 15:05:18.220
4,18,g3t2,Qual è il nome del simbolo al centro della ban...,Sole,2026-05-19 15:14:36.616

In [9]:
with open("Data/answer_set.json", 'r') as f:
        answer_set = json.load(f)

match_counts = []
for _, row in final_answer_df.iterrows():
        num_matches = 0
        answers = answer_set[row["topic_number"]]
        for answer_key in answers.keys():
                for answer in answers[answer_key]:
                        if answer.lower() in row["answer"].lower():
                        # print(row["answer"], ";", answer)
                                num_matches += 1
                                break
        print(row["uid"], row["topic_number"], row["answer"], num_matches)
        match_counts.append(num_matches)

final_answer_df["num_answer_matches"] = match_counts

17 g3t3 Pavone tigre 🐅 scimmia 🐵 leone cobra 5
17 g3t2 Rapreseta la ruota dellavitabhuddista, si chiama ashoka  2
17 g3t1 Il fiume si chiama  gange 1
18 g3t3 Tigre del bengala ,Leone asiatico ,rinoceronte Indiano ,barasingha ,Blackbuck 5
18 g3t2 Sole 0
18 g3t1 Il gange u 1
1 g3t3 Rinoceronte tigre Leone stambecco cervo 3
1 g3t2 Il simbolo della bandiera rappresenta una ruota 1
1 g3t1 Il fiume gange 1
2 g3t3 Tigre,leone,rinoceronte,barasingha,blackbuck. 5
2 g3t2 Ruota  1
2 g3t1 Fiume gange  1
3 g3t1 Gange 1
3 g3t3 Tigre ,Leone, rinoceronte ,Blackbuck barasingha  5
3 g3t2 Un sole 0
4 g3t2 Ashoka. La ruota della vita buddista 2
4 g3t3 Tigre del bengaline
Leone asiatico
Rinoceronte Indiano
Blackbuck
Barasingha  5
4 g3t1 Gange 1
5 g3t1 Gange, il fiume sacro agli indu e la popolazione indiana 1
5 g3t3 Natura selvaggia tra tigri e leoni terrelncognite magazine 0
5 g3t2 Bandiera indiana significato ashoka chakra simbolo della vita  1
6 g3t1 Gange 1
6 g3t3 Tigress del bengala Leone asiatico rinoceronte INDIANO barasingha blackbuck 5
6 g3t2 La ruota ashoka chakra 2
7 g3t2 E un. Sole blu 0
7 g3t3 Bengala Leone asiatico  rinoceronte indiano barasighna 2
7 g3t1 Gange il fiume sacro again indu e alla popolazione indiana 1
8 g3t3 Tigre elefante pavone rinoceronte scimmie 4
8 g3t2 Ruota con 24 raggi,blu nevy 1
8 g3t1 Gange 1
10 g4t3 Galassia del triangolo galassia del pegaso galassia della fenice 1
10 g4t2 Il primo animale che è andato nello spazio  era il cane Laika 2
10 g4t1 Io Europa ganimede e calisto 3
11 g4t3 Andromeda galassia del triangolo piccola nube di magellano
 3
11 g4t1 Callisto Europa Ganimede  Io 4
11 g4t2 Laika 1
12 g4t1 Io, Ganimede, Europa, Callisto  4
12 g4t2 È stato un cane di nome Laika 2
12 g4t3 Andromeda, galassia del triangolo M31, galassia sombrero M104 3
13 g4t1 Io, Europa, Ganimede e Callisto sono i 4 satelliti di Giove 4
13 g4t3 Le 3 galassie sono NGC3109,galassia di Andromeda galassia del triangolo  3
13 g4t2 Laika è stata il primo animale ed  è un cane  2
14 g4t1 Ganimede Callisto io Europa  4
14 g4t3 Andromeda del triangolo gruppo locale 2
14 g4t2 Un cane di nome Laika 2
15 g4t2 Il primo animale nello spazio è un cane e si chiamava Laika. 2
15 g4t3 Galassia di Andromeda Galassie di Fireworks Galassia del Triangolo 3
15 g4t1 Io Europa Ganimede e Callisto 4
16 g4t1 I satelliti maggiori di Giove si chiamano lune galileiane 1
16 g4t3 Andromeda, Galassia Sombrero ,Galassia del Triangolo
 3
16 g4t2 Il primo animali è stato un cane che si chiamava Laika 2
9 g4t2 Il primo animale  mandato nello spazio è state una cagnietta Di nome Laika  1
9 g4t1 Ganimede e Callisto  2
9 g4t3 Andromeda Triangolo Orsa Minore 3

In [10]:
final_answer_df.loc[final_answer_df["topic_number"]=="g3t1"]

,uid,topic_number,prompt,answer,timestamp,num_answer_matches
2,17,g3t1,Come si chiama il fiume sacro agli indiani?,Il fiume si chiama gange,2026-05-19 15:27:44.380,1
5,18,g3t1,Come si chiama il fiume sacro agli indiani?,Il gange u,2026-05-19 15:17:10.220,1
8,1,g3t1,Come si chiama il fiume sacro agli indiani?,Il fiume gange,2026-05-19 15:10:10.812,1
11,2,g3t1,Come si chiama il fiume sacro agli indiani?,Fiume gange,2026-05-19 15:15:05.518,1
12,3,g3t1,Come si chiama il fiume sacro agli indiani?,Gange,2026-05-19 14:51:32.588,1
17,4,g3t1,Come si chiama il fiume sacro agli indiani?,Gange,2026-05-19 15:21:00.731,1
18,5,g3t1,Come si chiama il fiume sacro agli indiani?,"Gange, il fiume sacro agli indu e la popolazio...",2026-05-19 14:58:33.130,1
21,6,g3t1,Come si chiama il fiume sacro agli indiani?,Gange,2026-05-19 14:52:28.940,1
26,7,g3t1,Come si chiama il fiume sacro agli indiani?,Gange il fiume sacro again indu e alla popolaz...,2026-05-19 15:05:34.776,1
29,8,g3t1,Come si chiama il fiume sacro agli indiani?,Gange,2026-05-19 15:16:38.128,1