In [2]:
import pandas as pd

## Corpus text analysis

In [3]:
from driver import clean_text

corpus = pd.read_excel("Data/corpus.xlsx")
corpus["text_content"] = corpus["text_content"].apply(lambda x: clean_text(x))
corpus.head()

,doc_id,url,html_content,text_content,scraping_source
0,d0,https://wwftravel.it/blog/viaggi/india-natura-...,"<body><p>""\n</p>\n<a class=""skip-link screen-r...",Vai al contenuto Home Blog Viaggi India natura...,manual-scraped
1,d1,https://www.terreincognitemagazine.it/natura-s...,"<body class=""single single-post postid-2526 si...",Homepage > CULTURA > MOSTRE > Natura selvaggia...,auto-scraped
2,d2,https://www.storicang.it/a/civilta-dellindo-i-...,"<body><p>""\n</p><div aria-hidden=""true"" class=...",La prospera civiltà della valle dell'Indo creb...,manual-scraped
3,d3,https://www.focusjunior.it/scuola/storia/chi-s...,"<body><div id=""fb-root""></div>\n<noscript></no...",FocusJunior.it Scuola Storia Chi sono gli Indi...,auto-scraped
4,d4,https://www.focusjunior.it/comportamento/feste...,"<body><div id=""fb-root""></div>\n<noscript></no...",FocusJunior.it Comportamento Feste Festa della...,auto-scraped

In [4]:
from driver import get_text_stats

text_stat_results = get_text_stats(corpus, "text_content")

corpus["content_len"] = text_stat_results["content_len"]
corpus["mean_aoa"] = text_stat_results["mean_aoa"]
corpus["mean_conc"] = text_stat_results["mean_conc"]
corpus["gulpease_index"] = text_stat_results["gulpease_index"]

  0%|          | 0/221 [00:00<?, ?it/s]

c:\Users\hrishitachakra\AppData\Local\anaconda3\envs\pt_env\lib\site-packages\numpy\_core\fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
c:\Users\hrishitachakra\AppData\Local\anaconda3\envs\pt_env\lib\site-packages\numpy\_core\_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

In [5]:
corpus.to_excel("Data/analysed_corpus.xlsx", index=False)

In [6]:
corpus.head()

,doc_id,url,html_content,text_content,scraping_source,content_len,mean_aoa,mean_conc,gulpease_index
0,d0,https://wwftravel.it/blog/viaggi/india-natura-...,"<body><p>""\n</p>\n<a class=""skip-link screen-r...",Vai al contenuto Home Blog Viaggi India natura...,manual-scraped,1389,5.314087,6.307500,51.666813
1,d1,https://www.terreincognitemagazine.it/natura-s...,"<body class=""single single-post postid-2526 si...",Homepage > CULTURA > MOSTRE > Natura selvaggia...,auto-scraped,1644,5.600471,5.939623,44.195174
2,d2,https://www.storicang.it/a/civilta-dellindo-i-...,"<body><p>""\n</p><div aria-hidden=""true"" class=...",La prospera civiltà della valle dell'Indo creb...,manual-scraped,1635,5.520000,6.553509,43.365193
3,d3,https://www.focusjunior.it/scuola/storia/chi-s...,"<body><div id=""fb-root""></div>\n<noscript></no...",FocusJunior.it Scuola Storia Chi sono gli Indi...,auto-scraped,1724,5.302264,5.982432,47.746429
4,d4,https://www.focusjunior.it/comportamento/feste...,"<body><div id=""fb-root""></div>\n<noscript></no...",FocusJunior.it Comportamento Feste Festa della...,auto-scraped,1140,4.143614,6.745545,52.684927

## Information distillation analysis

In [11]:
corpus_df = pd.read_excel("Data/analysed_corpus.xlsx")
explored_pages_df = pd.read_csv("Data/explored_pages.csv")
final_answer_df = pd.read_csv("Data/final_answer_df.csv")
results_navigation = pd.read_csv("Data/results_navigation.csv")

In [19]:
reqd_matches = {
    "g3t1": 1,
    "g3t2": 2,
    "g3t3": 5,
    "g4t1": 4,
    "g4t2": 2,
    "g4t3": 3
}

answer_accuracy = []
for _, row in final_answer_df.iterrows():
    rqd_num_matches = reqd_matches.get(row["topic_number"], None)
    answer_accuracy.append(min(row["num_answer_matches"], rqd_num_matches)/rqd_num_matches)

final_answer_df["answer_accuracy"] = answer_accuracy
final_answer_df["effective_answer"] = [int(ans_acc > 0.5) for ans_acc in final_answer_df["answer_accuracy"]]
final_answer_df.to_csv("Data/final_answer_df.csv", index=None, encoding="utf8")
final_answer_df.head()

,uid,topic_number,prompt,answer,timestamp,num_answer_matches,matched_keywords,answer_accuracy,effective_answer
0,1,g3t3,Quali sono 5 animali tipici dell'India?,Rinoceronte tigre Leone stambecco cervo,2026-05-19 14:56:19.153,4,"['tigre', 'rinoceronte', 'leone', 'cervo']",0.8,1
1,1,g3t2,Qual è il nome del simbolo al centro della ban...,Il simbolo della bandiera rappresenta una ruota,2026-05-19 15:06:18.848,1,['ruota'],0.5,0
2,1,g3t1,Come si chiama il fiume sacro agli indiani?,Il fiume gange,2026-05-19 15:10:10.812,1,['gange'],1.0,1
3,2,g3t3,Quali sono 5 animali tipici dell'India?,"Tigre,leone,rinoceronte,barasingha,blackbuck.",2026-05-19 14:58:07.578,5,"['tigre', 'rinoceronte', 'leone', 'barasingha'...",1.0,1
4,2,g3t2,Qual è il nome del simbolo al centro della ban...,Ruota,2026-05-19 15:10:30.790,1,['ruota'],0.5,0

In [13]:
results_navigation.head()

,uid,topic_number,qid,query,serp_id,url,title,snippet,rank,relevance_score,click_count,timestamp
0,1,g3t3,q1,Quali sono i cinque animali tipici dell india,serp1,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1,1,2,2026-05-19 14:51:27.687
1,1,g3t3,q1,Quali sono i cinque animali tipici dell india,serp1,https://www.terreincognitemagazine.it/natura-s...,"Natura selvaggia in India, tra tigri e leoni -...","\n Feb 17, 2017 ... O dei Giganti, vi...",2,1,0,2026-05-19 14:51:27.688
2,1,g3t3,q1,Quali sono i cinque animali tipici dell india,serp1,https://www.storicang.it/a/civilta-dellindo-i-...,"La civiltà dell'Indo, i misteri di un popolo d...","\n Jun 5, 2023 ... Sono note cinque m...",3,0,0,2026-05-19 14:51:27.689
3,1,g3t3,q1,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/scuola/storia/chi-s...,"Chi sono gli Indiani d'America, i nativi ameri...","\n Jun 6, 2024 ... Chi sono, da dove ...",4,0,0,2026-05-19 14:51:27.690
4,1,g3t3,q1,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/comportamento/feste...,Festa della mamma: come si festeggia nel resto...,\n Il dolce tipico per celebrare ques...,5,0,0,2026-05-19 14:51:27.691

In [20]:
explored_pages_df.head()

,uid,topic_number,url,exploreType,viewDurationInSeconds,timestamp,click_time
0,1,g3t3,https://wwftravel.it/blog/viaggi/india-natura-...,webpageOpened,NaN,2026-05-19 14:51:44.064,2026-05-19 14:51:43.444
1,1,g3t3,https://wwftravel.it/blog/viaggi/india-natura-...,webpageClosed,76.920,2026-05-19 14:53:00.984,2026-05-19 14:51:43.444
2,1,g3t3,https://wwftravel.it/blog/viaggi/india-natura-...,webpageOpened,NaN,2026-05-19 14:53:20.022,2026-05-19 14:53:19.408
3,1,g3t3,https://wwftravel.it/blog/viaggi/india-natura-...,webpageClosed,179.125,2026-05-19 14:56:19.147,2026-05-19 14:53:19.408
4,1,g3t2,https://it.gov-civ-guarda.pt/flag-india,webpageOpened,NaN,2026-05-19 15:02:49.238,2026-05-19 15:02:48.776

In [ ]:
mean_rel_time = [] # average time spent on relevant resources
meal_irrel_time = [] # average time spent on irrelevant resources

for _, row in final_answer_df.iterrows():
    rel_time = [] # time spent on relevant resources
    irrel_time = [] # time spent on irrelevant resources

    uid = row["uid"]
    topic_num = row["topic_number"]

    pages_explored = explored_pages_df.loc[(explored_pages_df["uid"]==uid) & (explored_pages_df["topic_number"]==topic_num) & (explored_pages_df["exploreType"]=="webpageClosed")]
    if len(pages_explored) == 0:
        print(uid, topic_num)
    else:
        for _, page in pages_explored.iterrows():