In [13]:
import json
import pandas as pd
import glob
import numpy as np
import driver

In [14]:
serp_df = pd.DataFrame()
clicked_results_df = pd.DataFrame()

for file_name in glob.glob("Data/3rd/*_FULL.log"):
    # print(file_name)
    with open(file_name, 'r') as f:
        result = [json.loads(x) for x in f.readlines()]

    # SERPs generated
    serp_temp_df = driver.get_generated_serps(result)
    serp_df = pd.concat([serp_df, serp_temp_df], ignore_index=True)

    # Clicked results
    clicked_results_temp_df = driver.get_clicked_results(result)
    clicked_results_df = pd.concat([clicked_results_df, clicked_results_temp_df], ignore_index=True)

for file_name in glob.glob("Data/4th/*_FULL.log"):
    # print(file_name)
    with open(file_name, 'r') as f:
        result = [json.loads(x) for x in f.readlines()]

    # SERPs generated
    serp_temp_df = driver.get_generated_serps(result)
    serp_df = pd.concat([serp_df, serp_temp_df], ignore_index=True)

    # Clicked results
    clicked_results_temp_df = driver.get_clicked_results(result)
    clicked_results_df = pd.concat([clicked_results_df, clicked_results_temp_df], ignore_index=True)


## assigning serp id
serp_num = 0
serp_id_list = []

for _, row in serp_df.iterrows():
    if row["rank"]==1 or pd.isna(row["rank"]):
        serp_num += 1
    serp_id_list.append("serp"+str(serp_num))

serp_df["serp_id"] = serp_id_list
serp_df = serp_df[["uid", "topic_number", "query", "serp_id", "url", "title", "snippet", "rank", "timestamp"]]

In [15]:
serp_df.head(20)

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp
0,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1.0,2026-05-19 14:50:54.636
1,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://www.terreincognitemagazine.it/natura-s...,"Natura selvaggia in India, tra tigri e leoni -...","\n Feb 17, 2017 ... O dei Giganti, vi...",2.0,2026-05-19 14:50:54.638
2,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://animalia.bio/it/india-animals,India - Animalia,"\n Flora e fauna ... L'India, ufficia...",3.0,2026-05-19 14:50:54.640
3,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://www.focusjunior.it/news/news-e-curiosi...,Quali sono gli sport più seguiti e praticati a...,"\n Il cricket è seguito da circa 2,5 ...",4.0,2026-05-19 14:50:54.644
4,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://www.goasia.it/geografia-natura-e-clima...,"Geografia, natura e clima dell'India - Go Asia",\n Molteplici varietà di animali sono...,5.0,2026-05-19 14:50:54.645
5,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://liceoberchet.edu.it/ricerche/geo4d_03/...,La Fauna,\n L'orso labiato ( Melursus ursinus)...,6.0,2026-05-19 14:50:54.647
6,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://www.focusjunior.it/animali/come-fanno-...,Come fanno i camaleonti a cambiare colore? - F...,\n ... della naturale pigmentazione g...,7.0,2026-05-19 14:50:54.648
7,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://www.focusjunior.it/animali/animali-sel...,I 10 serpenti più velenosi e letali del mondo ...,\n FocusJunior.it Animali Animali sel...,8.0,2026-05-19 14:50:54.650
8,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://www.focusjunior.it/scuola/storia/chi-s...,"Chi sono gli Indiani d'America, i nativi ameri...","\n Jun 6, 2024 ... L'abitazione tradi...",9.0,2026-05-19 14:50:54.652
9,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://www.focusjunior.it/tag/animali-in-esti...,animali in estinzione Archives - FocusJunior.it,\n Una rara tartaruga dal guscio moll...,10.0,2026-05-19 14:50:54.664
10,17,g3t3,Quali sono i 5 animali tipici del india,serp2,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1.0,2026-05-19 14:52:45.059
11,17,g3t3,Quali sono i 5 animali tipici del india,serp2,https://www.terreincognitemagazine.it/natura-s...,"Natura selvaggia in India, tra tigri e leoni -...","\n Feb 17, 2017 ... O dei Giganti, vi...",2.0,2026-05-19 14:52:45.062
12,17,g3t3,Quali sono i 5 animali tipici del india,serp2,https://animalia.bio/it/india-animals,India - Animalia,"\n Flora e fauna ... L'India, ufficia...",3.0,2026-05-19 14:52:45.064
13,17,g3t3,Quali sono i 5 animali tipici del india,serp2,https://www.focusjunior.it/news/news-e-curiosi...,Quali sono gli sport più seguiti e praticati a...,"\n Il cricket è seguito da circa 2,5 ...",4.0,2026-05-19 14:52:45.067
14,17,g3t3,Quali sono i 5 animali tipici del india,serp2,https://www.goasia.it/geografia-natura-e-clima...,"Geografia, natura e clima dell'India - Go Asia",\n Molteplici varietà di animali sono...,5.0,2026-05-19 14:52:45.069
15,17,g3t3,Quali sono i 5 animali tipici del india,serp2,https://liceoberchet.edu.it/ricerche/geo4d_03/...,La Fauna,\n L'orso labiato ( Melursus ursinus)...,6.0,2026-05-19 14:52:45.072
16,17,g3t3,Quali sono i 5 animali tipici del india,serp2,https://www.focusjunior.it/animali/come-fanno-...,Come fanno i camaleonti a cambiare colore? - F...,\n ... della naturale pigmentazione g...,7.0,2026-05-19 14:52:45.075
17,17,g3t3,Quali sono i 5 animali tipici del india,serp2,https://www.focusjunior.it/animali/animali-sel...,I 10 serpenti più velenosi e letali del mondo ...,\n FocusJunior.it Animali Animali sel...,8.0,2026-05-19 14:52:45.078
18,17,g3t3,Quali sono i 5 animali tipici del india,serp2,https://www.focusjunior.it/scuola/storia/chi-s...,"Chi sono gli Indiani d'America, i nativi ameri...","\n Jun 6, 2024 ... L'abitazione tradi...",9.0,2026-05-19 14:52:45.081
19,17,g3t3,Quali sono i 5 animali tipici del india,serp2,https://www.focusjunior.it/tag/animali-in-esti...,animali in estinzione Archives - FocusJunior.it,\n Una rara tartaruga dal guscio moll...,10.0,2026-05-19 14:52:45.083

In [16]:
clicked_results_df.head(40)

,uid,topic_number,query,url,rank,timestamp
0,17,g3t3,Quali sono i 5 animali tipici del india,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:51:29.948
1,17,g3t3,Quali sono i 5 animali tipici del india,https://www.focusjunior.it/animali/animali-sel...,8,2026-05-19 14:51:59.753
2,17,g3t3,Quali sono i 5 animali tipici del india,https://www.focusjunior.it/news/news-e-curiosi...,4,2026-05-19 14:53:05.134
3,17,g3t2,Quale il simbolo del la bandiera del india,https://liceoberchet.edu.it/ricerche/geo4d_03/...,1,2026-05-19 15:00:39.029
4,17,g3t2,Quale il simbolo del la bandiera del india,https://www.focusjunior.it/scuola/geografia/qu...,5,2026-05-19 15:01:01.003
5,17,g3t2,Quale il simbolo del la bandiera del india,https://www.focusjunior.it/scuola/geografia/le...,4,2026-05-19 15:01:38.336
6,17,g3t2,Quale ilsimbolo al centro della bandiera dell ...,https://sullestradedelmondo.it/bandiera-indiana/,1,2026-05-19 15:17:12.494
7,17,g3t1,Il nome del fiume sacro,https://www.beyondthetrip.net/2019/04/03/fiume...,1,2026-05-19 15:26:27.708
8,18,g3t3,Quali sono i cinque tipici animali dell l india,https://www.terreincognitemagazine.it/natura-s...,2,2026-05-19 14:53:05.881
9,18,g3t3,Quali sono i 5 cinque tipici animali dell l i...,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:55:22.455
10,18,g3t2,Simbolo della bandiera dell'india,https://it.gov-civ-guarda.pt/flag-india,6,2026-05-19 15:14:24.499
11,18,g3t1,Come si chiama il fiume sacro degli indiani,https://www.goasia.it/la-religione-gange-fiume...,1,2026-05-19 15:16:17.329
12,1,g3t3,Quali sono i cinque animali tipici dell india,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:51:43.444
13,1,g3t3,Quali sono i cinque animali tipici dell india,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:53:19.408
14,1,g3t2,Quale è il nome del simbolo al centro della ba...,https://it.gov-civ-guarda.pt/flag-india,1,2026-05-19 15:02:48.776
15,1,g3t1,Fiume sacro degli indiani,https://www.consciousjourneys.com/it/approfond...,2,2026-05-19 15:08:58.405
16,2,g3t3,Quali sono i 5 animali tipici dall'India,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:52:53.759
17,2,g3t2,Qual è il nome del simbolo al centro della b...,https://sullestradedelmondo.it/bandiera-indiana/,3,2026-05-19 15:09:25.575
18,2,g3t1,Come si chiama il fiume sacro agli indiani,https://www.consciousjourneys.com/it/approfond...,1,2026-05-19 15:14:18.095
19,3,g3t3,Quali sono 5 animali tipici dell'india,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:56:28.100
20,3,g3t2,Quale il nome del simbolo al centro della band...,https://mastroviaggiatore.it/saree/blog/lindia...,1,2026-05-19 15:05:39.212
21,3,g3t2,Quale il nome del simbolo al centro della band...,https://it.gov-civ-guarda.pt/flag-india,3,2026-05-19 15:06:00.133
22,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://it.gov-civ-guarda.pt/flag-india,7,2026-05-19 14:55:47.060
23,4,g3t2,Quale il simbolo dell'India,https://liceoberchet.edu.it/ricerche/geo4d_03/...,1,2026-05-19 15:06:06.889
24,4,g3t2,Quale il simbolo dell'India,https://www.focus.it/ambiente/animali/8-cose-c...,2,2026-05-19 15:06:28.655
25,4,g3t2,Quale il simbolo dell'India,https://www.skuola.net/geografia-medie/india-d...,3,2026-05-19 15:07:36.085
26,4,g3t2,Quale il simbolo dell'India,https://www.skuola.net/geografia-medie/india-d...,3,2026-05-19 15:07:49.996
27,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,2026-05-19 15:11:04.292
28,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,2026-05-19 15:12:03.487
29,4,g3t3,5 animali tipici dell'India,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 15:14:14.237
30,4,g3t3,5 animali tipici dell'India,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 15:17:21.809
31,4,g3t1,Fiume sacro indiano,https://www.goasia.it/la-religione-gange-fiume...,1,2026-05-19 15:20:26.846
32,5,g3t3,Quali sono 5 animali tipici dell india,https://www.terreincognitemagazine.it/natura-s...,2,2026-05-19 15:08:18.588
33,5,g3t2,Qual eil simbolo della bandiera india,https://sullestradedelmondo.it/bandiera-indiana/,1,2026-05-19 15:19:29.861
34,6,g3t3,Quali sono 5 animali tipici dell'india,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:56:05.417
35,6,g3t2,Quale il simbolo al centro della bandiera dell...,https://www.skuola.net/geografia-medie/india-d...,1,2026-05-19 15:08:05.059
36,6,g3t2,Simbolo andiera India,https://www.bandiere-nazionali.com/bandiera-in...,3,2026-05-19 15:11:31.642
37,6,g3t2,Simbolo andiera India,https://sullestradedelmondo.it/bandiera-indiana/,4,2026-05-19 15:13:24.460
38,8,g3t3,Quali sono 5 animali dell India,https://www.focusjunior.it/scuola/geografia/le...,5,2026-05-19 14:51:21.199
39,8,g3t3,Quali sono 5 animali dell India,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:51:42.534

In [17]:
clicked_results_df.dtypes

uid                      Int64
topic_number            object
query                   object
url                     object
rank                     Int64
timestamp       datetime64[ns]
dtype: object

In [18]:
associated_serp_ids = []

for _, row in clicked_results_df.iterrows():
    associated_serp = serp_df.loc[
        (serp_df["uid"]==row["uid"]) 
        & (serp_df["topic_number"]==row["topic_number"]) 
        & (serp_df["query"]==row["query"]) 
        & (serp_df["url"]==row["url"]) 
        & (serp_df["rank"]==row["rank"]) 
        & (serp_df["timestamp"]<row["timestamp"])
    ]

    if len(associated_serp) == 0:
        print(row)
        associated_serp_ids.append(None)

    elif len(associated_serp) > 1:
        # print(associated_serp)
        time_diff = np.inf
        for _, serp in associated_serp.iterrows():
            # print(serp)
            time_diff_compute = row["timestamp"] - serp["timestamp"]
            if time_diff >= time_diff_compute.total_seconds():
                correct_serp = serp["serp_id"]
                time_diff = time_diff_compute.total_seconds()
        associated_serp_ids.append(correct_serp)
    else:
        associated_serp_ids.append(associated_serp["serp_id"].values[0])

clicked_results_df["serp_id"] = associated_serp_ids

In [19]:
clicked_results_df.loc[pd.isna(clicked_results_df["serp_id"])]

Empty DataFrame
Columns: [uid, topic_number, query, url, rank, timestamp, serp_id]
Index: []

In [20]:
clicked_results_df.loc[clicked_results_df["timestamp"]=="2026-05-19 10:46:51.654"]

,uid,topic_number,query,url,rank,timestamp,serp_id
103,15,g4t2,Qual è stato il primo animale nello spazio e c...,https://www.storicang.it/foto-del-giorno/laika...,1,2026-05-19 10:46:51.654,serp101

In [21]:
clicked_results_df.loc[clicked_results_df["timestamp"]=="2026-05-19 10:51:16.099"]

,uid,topic_number,query,url,rank,timestamp,serp_id
104,15,g4t2,Qual è stato il primo animale nello spazio e c...,https://www.storicang.it/foto-del-giorno/laika...,1,2026-05-19 10:51:16.099,serp102

In [22]:
clicked_results_df.head(20)

,uid,topic_number,query,url,rank,timestamp,serp_id
0,17,g3t3,Quali sono i 5 animali tipici del india,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:51:29.948,serp1
1,17,g3t3,Quali sono i 5 animali tipici del india,https://www.focusjunior.it/animali/animali-sel...,8,2026-05-19 14:51:59.753,serp1
2,17,g3t3,Quali sono i 5 animali tipici del india,https://www.focusjunior.it/news/news-e-curiosi...,4,2026-05-19 14:53:05.134,serp2
3,17,g3t2,Quale il simbolo del la bandiera del india,https://liceoberchet.edu.it/ricerche/geo4d_03/...,1,2026-05-19 15:00:39.029,serp3
4,17,g3t2,Quale il simbolo del la bandiera del india,https://www.focusjunior.it/scuola/geografia/qu...,5,2026-05-19 15:01:01.003,serp3
5,17,g3t2,Quale il simbolo del la bandiera del india,https://www.focusjunior.it/scuola/geografia/le...,4,2026-05-19 15:01:38.336,serp4
6,17,g3t2,Quale ilsimbolo al centro della bandiera dell ...,https://sullestradedelmondo.it/bandiera-indiana/,1,2026-05-19 15:17:12.494,serp6
7,17,g3t1,Il nome del fiume sacro,https://www.beyondthetrip.net/2019/04/03/fiume...,1,2026-05-19 15:26:27.708,serp7
8,18,g3t3,Quali sono i cinque tipici animali dell l india,https://www.terreincognitemagazine.it/natura-s...,2,2026-05-19 14:53:05.881,serp8
9,18,g3t3,Quali sono i 5 cinque tipici animali dell l i...,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:55:22.455,serp9
10,18,g3t2,Simbolo della bandiera dell'india,https://it.gov-civ-guarda.pt/flag-india,6,2026-05-19 15:14:24.499,serp11
11,18,g3t1,Come si chiama il fiume sacro degli indiani,https://www.goasia.it/la-religione-gange-fiume...,1,2026-05-19 15:16:17.329,serp12
12,1,g3t3,Quali sono i cinque animali tipici dell india,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:51:43.444,serp13
13,1,g3t3,Quali sono i cinque animali tipici dell india,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:53:19.408,serp13
14,1,g3t2,Quale è il nome del simbolo al centro della ba...,https://it.gov-civ-guarda.pt/flag-india,1,2026-05-19 15:02:48.776,serp14
15,1,g3t1,Fiume sacro degli indiani,https://www.consciousjourneys.com/it/approfond...,2,2026-05-19 15:08:58.405,serp15
16,2,g3t3,Quali sono i 5 animali tipici dall'India,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:52:53.759,serp17
17,2,g3t2,Qual è il nome del simbolo al centro della b...,https://sullestradedelmondo.it/bandiera-indiana/,3,2026-05-19 15:09:25.575,serp19
18,2,g3t1,Come si chiama il fiume sacro agli indiani,https://www.consciousjourneys.com/it/approfond...,1,2026-05-19 15:14:18.095,serp20
19,3,g3t3,Quali sono 5 animali tipici dell'india,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:56:28.100,serp22

In [ ]:
df = pd.DataFrame(clicked_results_df.groupby(["uid", "topic_number", "query", "rank", "serp_id"])["url"].value_counts()).reset_index()

serp_df["click_count"] = 0
for _, row in df.iterrows():
    serp_df_row = serp_df.loc[(serp_df["serp_id"]==row["serp_id"])&(serp_df["url"])]

,uid,topic_number,query,rank,serp_id,url,count
2,1,g3t3,Quali sono i cinque animali tipici dell india,1,serp13,https://wwftravel.it/blog/viaggi/india-natura-...,2
10,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,2,serp29,https://sullestradedelmondo.it/bandiera-indiana/,2
14,4,g3t2,Quale il simbolo dell'India,3,serp28,https://www.skuola.net/geografia-medie/india-d...,2
15,4,g3t3,5 animali tipici dell'India,1,serp30,https://wwftravel.it/blog/viaggi/india-natura-...,2
23,8,g3t3,Quali sono 5 animali dell India,1,serp59,https://wwftravel.it/blog/viaggi/india-natura-...,2
24,8,g3t3,Quali sono 5 animali dell India,4,serp60,https://animalia.bio/it/india-animals,2
26,9,g4t1,Come si chiamano i satelliti maggiori di Giove,1,serp119,https://www.astronomitaly.com/blog/astronomy-p...,3
34,9,g4t2,Quale è il primo animale nello spazio e come s...,2,serp116,https://www.focusjunior.it/scienza/spazio/laik...,2
43,9,g4t3,3 galassie oltre la nostra,9,serp122,https://www.focusjunior.it/scienza/spazio/stel...,3
44,9,g4t3,Quali sono i nomi di altre 3 galassie oltre la...,1,serp120,https://www.focusjunior.it/scienza/spazio/stel...,2
45,9,g4t3,Quali sono i nomi di altre 3 galassie oltre la...,2,serp120,https://123stella.astronomiamo.it/Fase.aspx?Ar...,3
46,9,g4t3,Quali sono i nomi di altre 3 galassie oltre la...,3,serp120,https://www.castfvg.it/galassie/gruppo_locale/...,2
47,9,g4t3,Quali sono i nomi di altre 3 galassie oltre la...,4,serp120,https://www.focusjunior.it/content/uploads/sit...,2
48,10,g4t2,qual'è stato il primo animale nello spazio e c...,1,serp70,https://www.storicang.it/foto-del-giorno/laika...,2
54,11,g4t2,Qual è stato il primo animale nello spazio e c...,1,serp78,https://www.storicang.it/foto-del-giorno/laika...,2
55,11,g4t3,Nomi delle 3 galassia,5,serp75,https://www.castfvg.it/galassie/gruppo_locale/...,3
59,11,g4t3,Quali sono i nomi di altre 3 galassie oltre la...,1,serp73,https://www.focusjunior.it/scienza/spazio/stel...,3
64,12,g4t2,Qual è stato il primo animale nello spazio e c...,1,serp81,https://www.storicang.it/foto-del-giorno/laika...,4
68,12,g4t3,3 Galassie oltre la nostra,14,serp83,https://astroscopehub.com/nomi-di-galassie/,2
70,12,g4t3,Quali sono i nomi di altre 3 galassie oltre la...,1,serp82,https://www.focusjunior.it/scienza/spazio/stel...,2
71,12,g4t3,Quali sono i nomi di altre 3 galassie oltre la...,2,serp82,https://123stella.astronomiamo.it/Fase.aspx?Ar...,4
73,12,g4t3,Quali sono i nomi di altre 3 galassie oltre la...,4,serp82,https://www.focusjunior.it/content/uploads/sit...,2
76,13,g4t1,come si chiamano i satelliti di giove,1,serp87,https://www.astronomitaly.com/blog/astronomy-p...,4
77,13,g4t1,come si chiamano i satelliti di giove,7,serp87,https://edu.inaf.it/astrofoto/giove-satelliti-...,2
78,13,g4t2,Qual è stato il primo animale nello spazio e c...,1,serp90,https://www.storicang.it/foto-del-giorno/laika...,2
89,15,g4t2,Qual è stato il primo animale nello spazio e c...,1,serp102,https://www.storicang.it/foto-del-giorno/laika...,4
91,15,g4t3,Nomi di altre galassie,3,serp107,https://www.latorredelsole.it/2025/09/05/m-31-...,3
93,15,g4t3,Quali sono i nomi di altre 3 galassie oltre la...,1,serp104,https://www.focusjunior.it/scienza/spazio/stel...,2
96,15,g4t3,Quali sono i nomi di altre 3 galassie oltre la...,4,serp104,https://www.focusjunior.it/content/uploads/sit...,2
101,15,g4t3,Quali sono i nomi di altre 3 galassie oltre la...,1,serp105,https://www.focusjunior.it/scienza/spazio/stel...,2
105,16,g4t3,Quali sono i nomi di 3 galassie oltre la nostra,3,serp114,https://www.focusjunior.it/scienza/spazio/i-pi...,2

In [24]:
serp_df.loc[serp_df["serp_id"]=="serp119"]

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp
945,9,g4t1,Come si chiamano i satelliti maggiori di Giove,serp119,https://www.astronomitaly.com/blog/astronomy-p...,"Io, Europa, Ganimede e Callisto: guida ai 4 sa...","\n Mar 19, 2024 ... Io, Europa, Ganim...",1.0,2026-05-19 10:55:55.513
946,9,g4t1,Come si chiamano i satelliti maggiori di Giove,serp119,https://starwalk.space/it/news/jupiter-galilea...,"Lune di Giove: quante sono, nomi e ordine | Lu...",\n Quante lune ha Giove nel 2026? Qua...,2.0,2026-05-19 10:55:55.519
947,9,g4t1,Come si chiamano i satelliti maggiori di Giove,serp119,https://edu.inaf.it/astrofoto/giove-satelliti-...,Giove e i suoi satelliti - EduINAF,"\n Dec 3, 2021 ... Il pianeta è compo...",3.0,2026-05-19 10:55:55.524
948,9,g4t1,Come si chiamano i satelliti maggiori di Giove,serp119,https://www.focusjunior.it/news/news-e-curiosi...,Perché alcuni pianeti hanno gli anelli? - Focu...,"\n Mar 18, 2024 ... Gli anelli planet...",4.0,2026-05-19 10:55:55.531
949,9,g4t1,Come si chiamano i satelliti maggiori di Giove,serp119,https://www.focusjunior.it/news/lallineamento-...,"Oggi, 28 febbraio 2025, si verificherà l'allin...","\n Feb 28, 2025 ... ... di Venere, Ma...",5.0,2026-05-19 10:55:55.543
950,9,g4t1,Come si chiamano i satelliti maggiori di Giove,serp119,https://www.focusjunior.it/scienza/spazio/pian...,Quanto dura un giorno sugli altri pianeti? - F...,\n Quanto può durare un giorno su alt...,6.0,2026-05-19 10:55:55.546