In [ ]:
import json
import pandas as pd
import glob
import numpy as np
import driver

In [ ]:
serp_df = pd.DataFrame()
clicked_results_df = pd.DataFrame()

for file_name in glob.glob("Data/3rd/*_FULL.log"):
    # print(file_name)
    with open(file_name, 'r') as f:
        result = [json.loads(x) for x in f.readlines()]

    # SERPs generated
    serp_temp_df = driver.get_generated_serps(result)
    serp_df = pd.concat([serp_df, serp_temp_df], ignore_index=True)

    # Clicked results
    clicked_results_temp_df = driver.get_clicked_results(result)
    clicked_results_df = pd.concat([clicked_results_df, clicked_results_temp_df], ignore_index=True)

for file_name in glob.glob("Data/4th/*_FULL.log"):
    # print(file_name)
    with open(file_name, 'r') as f:
        result = [json.loads(x) for x in f.readlines()]

    # SERPs generated
    serp_temp_df = driver.get_generated_serps(result)
    serp_df = pd.concat([serp_df, serp_temp_df], ignore_index=True)

    # Clicked results
    clicked_results_temp_df = driver.get_clicked_results(result)
    clicked_results_df = pd.concat([clicked_results_df, clicked_results_temp_df], ignore_index=True)


## assigning serp id
serp_num = 0
serp_id_list = []

for _, row in serp_df.iterrows():
    if row["rank"]==1 or pd.isna(row["rank"]):
        serp_num += 1
    serp_id_list.append("serp"+str(serp_num))

serp_df["serp_id"] = serp_id_list
serp_df = serp_df[["uid", "topic_number", "query", "serp_id", "url", "title", "snippet", "rank", "timestamp"]]

In [ ]:
serp_df.head()

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp
0,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1.0,2026-05-19T14:50:54.636
1,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://www.terreincognitemagazine.it/natura-s...,"Natura selvaggia in India, tra tigri e leoni -...","\n Feb 17, 2017 ... O dei Giganti, vi...",2.0,2026-05-19T14:50:54.638
2,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://animalia.bio/it/india-animals,India - Animalia,"\n Flora e fauna ... L'India, ufficia...",3.0,2026-05-19T14:50:54.640
3,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://www.focusjunior.it/news/news-e-curiosi...,Quali sono gli sport più seguiti e praticati a...,"\n Il cricket è seguito da circa 2,5 ...",4.0,2026-05-19T14:50:54.644
4,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://www.goasia.it/geografia-natura-e-clima...,"Geografia, natura e clima dell'India - Go Asia",\n Molteplici varietà di animali sono...,5.0,2026-05-19T14:50:54.645

In [ ]:
clicked_results_df.head()

,uid,topic_number,query,url,rank,timestamp
0,17,g3t3,Quali sono i 5 animali tipici del india,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19T14:51:29.948
1,17,g3t3,Quali sono i 5 animali tipici del india,https://www.focusjunior.it/animali/animali-sel...,8,2026-05-19T14:51:59.753
2,17,g3t3,Quali sono i 5 animali tipici del india,https://www.focusjunior.it/news/news-e-curiosi...,4,2026-05-19T14:53:05.134
3,17,g3t2,Quale il simbolo del la bandiera del india,https://liceoberchet.edu.it/ricerche/geo4d_03/...,1,2026-05-19T15:00:39.029
4,17,g3t2,Quale il simbolo del la bandiera del india,https://www.focusjunior.it/scuola/geografia/qu...,5,2026-05-19T15:01:01.003

In [ ]:
clicked_results_df.dtypes

uid              int64
topic_number    object
query           object
url             object
rank            object
timestamp       object
dtype: object

In [ ]:
for _, row in clicked_results_df.iterrows():
    associated_serp = serp_df.loc[(serp_df["uid"]==row["uid"])&(serp_df["topic_number"]==row["topic_number"])&(serp_df["query"]==row["query"])&(serp_df["url"]==row["url"])&(serp_df["rank"]==row["rank"])]